domain-needed
bogus-priv
resolv-file=/var/default/resolv.conf
expand-hosts
domain=utopia.net
dhcp-leasefile=/nvram/dnsmasq.leases
dhcp-lease-max=252
dhcp-hostsfile=/etc/dhcp_static_hosts
interface=brlan0
dhcp-range=192.168.1.2,192.168.1.253,255.255.255.0,7d
address=/#/192.168.1.1
dhcp-option=252,"\n"
